title: Alma Soria
#logo: /assets/img/headshot_circle.png
description: Google Certified Professional Cloud Architect | Machine Learning Analyst Student | BSc Biopharmaceutical Chemistry
show_downloads: true
theme: jekyll-theme-minimal
